# renovate: datasource=github-tags depName=balena-io-experimental/browser versioning=loose
ARG BROWSER_VERSION=2.7.1
FROM bh.cr/balenalabs/browser-%%BALENA_ARCH%%/$BROWSER_VERSION AS base

RUN install_packages cec-utils
